---
- name: "update packages."
  become: true
  apt:
    update_cache: yes

- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt -y install nodejs

- name: "installing npm"
  become: true
  apt:
    name: npm
    update_cache: yes
    state: latest

- name: "Install PM2 Globally"
  npm:
    name: PM2
    global: yes
    production: yes
    state: present